#!/usr/local/bin/perl

## http://load.sh:3000/blog/2016/11/18/watch-moviebox-on-linux/

use 5.010;
use warnings;
use strict;

use Getopt::Std;
use Filesys::Notify::Simple;
use JSON::PP;
use Net::OpenSSH;

# todo 
# activator send libactivator.sms.compose-message
# moviebox-connect -l | pbcopy

my $opt = {}; 
getopts('u:i:p:slkg', $opt);
# get config
my $c = decode_json scalar <DATA>;

status() if $opt->{s} or $opt->{k};
playlist() if $opt->{g} or $opt->{l};

# init 
system("cp $c->{ios}->{cache} $c->{ios}->{old_cache}") unless -f $c->{ios}->{old_cache};
system("echo '$c->{ios}->{user_template}' > $c->{ios}->{user}") unless -f $c->{ios}->{user};

# status
sub status {
    my $pids = ' ';
    my @ps = grep{ /moviebox-connect/ } qx{ ps aux };
    for(@ps){ push my @pid, split(" ", $_); $pids .= " $pid[1]" unless $pid[1] eq $$ }
    if(exists $opt->{k}){ system("kill -9 $pids");say "killed: $pids"; die bless [], 'Dies'; }
    if($pids eq ' '){ say "$0: not running" } else { say "$0: $pids" }
    
    die bless [], 'Dies';
    package Dies;
    use overload '""' => 'dies';
    sub dies { return '' }
}

# get last URL
sub url {
    my $diff = `diff $c->{ios}->{cache} $c->{ios}->{old_cache}`;
    open my $fh,'<',\$diff;
    while(<$fh>){
        if(/\.mp4/){
            s/(.*key\>?)(http:\/\/.*?)(<\/.*)/$2/;
            open(my $fh,'>',$c->{ios}->{url});
            print $fh $2;
            close $fh;
            system("cp $c->{ios}->{cache} $c->{ios}->{old_cache}");
        }
    }
}

# write playlist file
sub playlist {
    open(my $fh,'<',$c->{ios}->{url});
    my $url = <$fh>;
    close $fh;

    if($opt->{l}){ print $url and die }

    my @cmd = ( "echo \'$c->{playlist}->{head}$url$c->{playlist}->{tail}\' > ~/Desktop/moviebox.xspf && export DISPLAY=:0 && vlc ~/Desktop/moviebox.xspf > /dev/null 2>&1" );

    my $ssh;
    if($opt->{u} and $opt->{i} and $opt->{p}){ 
        #--- get user details from command line
        $ssh = Net::OpenSSH->new("$opt->{u}:$opt->{p}\@$opt->{i}");
    } else { 
        #--- get user details from config file
        if(-f $c->{ios}->{user}){
            local $/;
            open(my $fh,'<', $c->{ios}->{user});
            my $user = decode_json scalar <$fh>;
            $ssh = Net::OpenSSH->new("$user->{username}:$user->{password}\@$user->{ipaddress}");
        }
    }
    $ssh->capture(@cmd);
    die;
}

$| = 1;
my $watcher = Filesys::Notify::Simple->new([ $c->{ios}->{cache} ]);
while(1){ $watcher->wait( sub{ url() for @_ }) }


=head1 NAME

moviebox-connect

=cut

=head1 SYNOPSIS

Creates VLC playlist ~/Desktop/moviebox.xspf on remote host for last movie played on iOS MovieBox app. 

=cut

=head1 USAGE

Create playlist for VLC and send it to ~/Desktop/moviebox.xspf on username@ipaddress

    moviebox-connect -u username -i ipaddress -p password

or fill remote host details in ~/moviebox-connect.json and start without any option

    moviebox-connect

Just print URL and exit
    
    moviebox-connect -l

See if moviebox-connect is running

    moviebox-connect -s

Stop moviebox-connect

    moviebox-connect -k

=cut

__DATA__
{"ios":{"cache":"/private/var/tmp/MediaCache/diskcacherepository.plist","old_cache":"/private/var/mobile/.moviebox-connect","playlist":"/private/var/tmp/moviebox.xspf","url":"/tmp/.moviebox-connect","user":"/var/mobile/moviebox-connect.json","user_template":"{\"username\":\"fill\",\"ipaddress\":\"fill\",\"password\":\"fill\"}"},"playlist":{"head":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><playlist xmlns=\"http://xspf.org/ns/0/\" xmlns:vlc=\"http://www.videolan.org/vlc/playlist/ns/0/\" version=\"1\"><title>Playlist</title><trackList><track><location>","url":"","tail":"</location><extension application=\"http://www.videolan.org/vlc/playlist/0\"><vlc:id>0</vlc:id><vlc:option>network-caching=1000</vlc:option></extension></track></trackList><extension application=\"http://www.videolan.org/vlc/playlist/0\"><vlc:item tid=\"0\"/></extension></playlist>"}}
